source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PlayingCardsExample', :exclusive => true do
  pod "PlayingCards-Swift", :path => "../"
end

target 'PlayingCardsTests', :exclusive => true do
  pod "PlayingCards-Swift", :path => "../"

  
end
